<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="API.com.project.api.SAIL.SAIL_CourseRegistrationTest" tests="8" time="41.687" ignored="0" failures="2" timestamp="05 Sep 2017 19:02:54 GMT" skipped="0" hostname="WFXD481D7D98814" errors="0">
  <testcase name="T7_test_No_Of_Records_If_Offset_And_Max_Are_Same" time="2.688" classname="API.com.project.api.SAIL.SAIL_CourseRegistrationTest"/>
  <testcase name="T1_test_Http_Status_Code_For_The_Programs_API" time="11.577" classname="API.com.project.api.SAIL.SAIL_CourseRegistrationTest"/>
  <testcase name="T4_test_OffSet_And_Max_When_Set_To_Same_Value_Recors_Are_Displayed_While_Using_Pagesize" time="3.033" classname="API.com.project.api.SAIL.SAIL_CourseRegistrationTest"/>
  <testcase name="T3_test_More_Than_Records_Are_Returned_From_The_Call" time="0.004" classname="API.com.project.api.SAIL.SAIL_CourseRegistrationTest"/>
  <testcase name="T5_test_Check_A_SpecificRecord" time="8.615" classname="API.com.project.api.SAIL.SAIL_CourseRegistrationTest">
    <failure type="java.lang.AssertionError" message="Invalid key instructors found expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Invalid key instructors found expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:305)
	at Parser.Parser.checkValuesForKeysInResponseInsideRecordRange(Parser.java:160)
	at Parser.Parser.checkKeyValueForResponseInRecordNumber(Parser.java:82)
	at API.com.project.api.SAIL.SAIL_CourseRegistrationTest.T5_test_Check_A_SpecificRecord(SAIL_CourseRegistrationTest.java:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </failure>
  </testcase> <!-- T5_test_Check_A_SpecificRecord -->
  <testcase name="T8_test_No_Of_Records_If_OfSet_IS_SET_TO_0" time="8.131" classname="API.com.project.api.SAIL.SAIL_CourseRegistrationTest"/>
  <testcase name="T6_test_Check_Records_In_Range" time="7.634" classname="API.com.project.api.SAIL.SAIL_CourseRegistrationTest">
    <failure type="java.lang.AssertionError" message="Invalid key course_registrations found expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Invalid key course_registrations found expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:305)
	at Parser.Parser.checkValuesForKeysInResponseInsideRecordRange(Parser.java:160)
	at API.com.project.api.SAIL.SAIL_CourseRegistrationTest.T6_test_Check_Records_In_Range(SAIL_CourseRegistrationTest.java:144)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </failure>
  </testcase> <!-- T6_test_Check_Records_In_Range -->
  <testcase name="T2_test_All_Headers_Are_Present_In_The_Response" time="0.005" classname="API.com.project.api.SAIL.SAIL_CourseRegistrationTest"/>
</testsuite> <!-- API.com.project.api.SAIL.SAIL_CourseRegistrationTest -->
